/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.samples.fbo.big.titles.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BigTitle service. Represents a row in the &quot;BIGTITLE_BigTitle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.samples.fbo.big.titles.model.impl.BigTitleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.samples.fbo.big.titles.model.impl.BigTitleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BigTitle
 * @generated
 */
@ProviderType
public interface BigTitleModel extends BaseModel<BigTitle>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a big title model instance should use the {@link BigTitle} interface instead.
	 */

	/**
	 * Returns the primary key of this big title.
	 *
	 * @return the primary key of this big title
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this big title.
	 *
	 * @param primaryKey the primary key of this big title
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the big title ID of this big title.
	 *
	 * @return the big title ID of this big title
	 */
	public long getBigTitleId();

	/**
	 * Sets the big title ID of this big title.
	 *
	 * @param bigTitleId the big title ID of this big title
	 */
	public void setBigTitleId(long bigTitleId);

	/**
	 * Returns the company ID of this big title.
	 *
	 * @return the company ID of this big title
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this big title.
	 *
	 * @param companyId the company ID of this big title
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the article pk of this big title.
	 *
	 * @return the article pk of this big title
	 */
	public long getArticlePK();

	/**
	 * Sets the article pk of this big title.
	 *
	 * @param articlePK the article pk of this big title
	 */
	public void setArticlePK(long articlePK);

	/**
	 * Returns the title of this big title.
	 *
	 * @return the title of this big title
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this big title.
	 *
	 * @param title the title of this big title
	 */
	public void setTitle(String title);

	/**
	 * Returns the language ID of this big title.
	 *
	 * @return the language ID of this big title
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this big title.
	 *
	 * @param languageId the language ID of this big title
	 */
	public void setLanguageId(String languageId);

}